Update requirements.txt to newer attrs
Ended up with this error with the 19* version
ImportError: cannot import name 'resolve_types' from 'attr' (/Users/kachenjr/IdeaProjects/amazon-textract-a2i-pdf/venv/lib/python3.8/site-packages/attr/__init__.py)

Updating to the 21.0.2 version ( latest ) resolved the issue.